### ISSUE TITLE
`isWebP` name should match on URL and Data

### ISSUE THREAD

**Issue by jeffreybergier** [TimOliver/WebPKit#1]
I think it makes sense that `isWebPFormat` and `isWebPFile` should both be changed to `isWebP`. Whether its a file or not is clear from the original object type.

https://github.com/TimOliver/WebPKit/blob/f22b26564fcc4393454b250487c62a613ff3e5e5/WebPKit/Decoding/Utilities/URL%2BWebPDecoding.swift#L35

https://github.com/TimOliver/WebPKit/blob/f22b26564fcc4393454b250487c62a613ff3e5e5/WebPKit/Decoding/Utilities/Data%2BWebPDecoding.swift#L31

**Comment by TimOliver** [comment]
Thanks Jeff! I just changed it to that. :D
