### ISSUE TITLE
Deployment target question.

### ISSUE THREAD

**Issue by daisuke-t-jp** [TimOliver/WebPKit#13]
Hi,

The deployment target for iOS and tvOS has changed from 9 to 12, is this correct?

In the README, the deployment target is still 9.

Thanks.

https://github.com/TimOliver/WebPKit/commit/9a68f2c7a840190a7137b42d8ca5bb4e44891e49#diff-4e72e7b6e03fb8627c9269f4537d20d97276bdec1dbd3fb9da4a83f353a3d5d7

**Comment by TimOliver** [comment]
Hi there @daisuke-t-jp!

Ahh yep, the project itself should still deploy to iOS 9 without issue. I've only set the Xcode demo project to iOS 12, and (I can't remember exactly why) I think I did that because the demo apps are using iOS 12 specific APIs.

But this library should still work with no issues on iOS 9. If it is indeed not working, please let me know. Thanks! :)

**Comment by daisuke-t-jp** [comment]
Hi, @TimOliver

Thanks for your reply.

The demo and the library target changed at the same time.
This library is currently targeted for iOS / tvOS 12 and above.

https://github.com/TimOliver/WebPKit/blob/2f0d33abad63ff81b7bf9360091d220255136566/WebPKit.xcodeproj/project.pbxproj#L2026

https://github.com/TimOliver/WebPKit/blob/2f0d33abad63ff81b7bf9360091d220255136566/WebPKit.xcodeproj/project.pbxproj#L2062

https://github.com/TimOliver/WebPKit/blob/2f0d33abad63ff81b7bf9360091d220255136566/WebPKit.xcodeproj/project.pbxproj#L2255

https://github.com/TimOliver/WebPKit/blob/2f0d33abad63ff81b7bf9360091d220255136566/WebPKit.xcodeproj/project.pbxproj#L2288

I try to build the demo app targeting iOS 9, I get an error.

<img width="500" alt="scr" src="https://user-images.githubusercontent.com/45647069/100351445-cbc13d80-302e-11eb-90b5-a7a45406fbea.png">

I made a pull request, So if you like, merge it. #14 

Thanks.

**Comment by TimOliver** [comment]
Oh dear! Okay then! I didn't know that was actually happening! I have no idea why I set that then. 😅

Thanks for the PR! I'll merge it right away!
