### ISSUE TITLE
CocoaPod Installation - CGImage error

### ISSUE THREAD

**Issue by DwieDave** [TimOliver/WebPKit#15]
Hello Tim,
I've tried installing WebPKit via CocoaPods and have several issues:
When installing without version or github specification the majority of the features are missing because the pod is very outdated.
I've then added it via the .git URL and the Encoding functionality was back.
The recent problem now is that Xcode throws a compiler error that it cannot find the cgImage.webpdata() function
(Attached Screenshot)

<img width="1910" alt="image" src="https://user-images.githubusercontent.com/15933094/163796823-5752a724-8c7b-4c52-be3f-73c544304dc7.png">

If you got any idea on whats going wrong please hit me up.

**Comment by TimOliver** [comment]
HI there Dave! Thanks for giving the library a try!

Ahhh, you're right! I didn't properly set up the import mechanism to import the `libwebp` module from CocoaPods in the `CGImage` source file. Sorry about that!

I just pushed a new version to CocoaPods that fixes this (And tested it locally while I was at it). Try and do a `pod update` now and let me know if it's working for you now!

**Comment by DwieDave** [comment]
Thank you for the fast response!
I will check it out

**Comment by TimOliver** [comment]
Hey @DwieDave!

I'm 99% sure this is fixed so I'm going to close the issue now. If you get the chance to test it, and it's still broken for you, please feel free to re-open this issue. :)

Thanks!
